name = "auto-expand-shopify"
type = "javascript"

account_id = "d6298858ea89d131e3589c82b834d95c"
compatibility_date = "2025-05-21"
compatibility_flags = ["nodejs_compat"]

main = "src/shopify.js"

[vars]
CF_ACCOUNT_ID        = "${{ secrets.CF_ACCOUNT_ID }}"
CLOUDFLARE_API_TOKEN = "${{ secrets.CF_API_TOKEN }}"
SHOPIFY_WEBHOOK_SECRET = ""
